# Genera un .cpp con los recursos web embebidos como arrays de bytes.
#   cmake -DOUT=salida.cpp -DSPECS="ruta_origen|/ruta/url@@..." [-DMIMES="..."] -P embed_assets.cmake
# Uso interno de CMakeLists.txt (la GUI se sirve desde el propio ejecutable, sin ficheros sueltos).

function(mime_for url out_var)
    if(url MATCHES "[.]html$")
        set(m "text/html; charset=utf-8")
    elseif(url MATCHES "[.]js$")
        set(m "text/javascript; charset=utf-8")
    elseif(url MATCHES "[.]css$")
        set(m "text/css; charset=utf-8")
    elseif(url MATCHES "[.]svg$")
        set(m "image/svg+xml")
    elseif(url MATCHES "[.]json$")
        set(m "application/json; charset=utf-8")
    else()
        set(m "application/octet-stream")
    endif()
    set(${out_var} "${m}" PARENT_SCOPE)
endfunction()

set(body "// ARCHIVO GENERADO por cmake/embed_assets.cmake -- no editar a mano.\n#include \"web_assets.hpp\"\n\nnamespace mc::gui {\nnamespace {\n")
set(table "")
set(idx 0)
string(REPLACE "@@" ";" SPEC_LIST "${SPECS}")
foreach(spec IN LISTS SPEC_LIST)
    string(REPLACE "|" ";" parts "${spec}")
    list(GET parts 0 src)
    list(GET parts 1 url)
    file(READ "${src}" hex HEX)
    string(LENGTH "${hex}" hexlen)
    math(EXPR nbytes "${hexlen} / 2")
    # Se trocea para que la sustitución por regex trabaje con cadenas moderadas
    set(arr "")
    set(pos 0)
    while(pos LESS hexlen)
        string(SUBSTRING "${hex}" ${pos} 65536 piece)
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," piece "${piece}")
        string(APPEND arr "${piece}\n")
        math(EXPR pos "${pos} + 65536")
    endwhile()
    mime_for("${url}" mime)
    string(APPEND body "const unsigned char a${idx}[] = {\n${arr}0};\n")
    string(APPEND table "    {\"${url}\", \"${mime}\", a${idx}, ${nbytes}},\n")
    math(EXPR idx "${idx} + 1")
endforeach()
string(APPEND body "const EmbeddedAsset kAssets[] = {\n${table}};\n} // namespace\n\nconst EmbeddedAsset* embedded_assets(std::size_t* n) {\n    *n = sizeof(kAssets) / sizeof(kAssets[0]);\n    return kAssets;\n}\n\n} // namespace mc::gui\n")
file(WRITE "${OUT}" "${body}")
